import {Inter} from 'next/font/google'
import './globals.css'
import {Providers} from './providers'

const inter = Inter({subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
    <html lang='en' className={inter.className} suppressHydrationWarning>
      <body className='bg-gray-50 dark:bg-slate-800'>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
